# Generated by Django 5.1.1 on 2024-09-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='courtbooking',
            name='court',
        ),
        migrations.DeleteModel(
            name='Court',
        ),
        migrations.DeleteModel(
            name='CourtBooking',
        ),
    ]
